services:
  sm_airbrake.airbrake_exception.listener:
    class: SM\AirbrakeBundle\Listener\AirbrakeExceptionListener
    arguments:
      - "%sm_airbrake.listener_enabled%"
      - "@sm_airbrake.airbrake.service"
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
